Repository vinidomeli/tlm-frescos-api, pull requests merged in 2021-07, with the labels that each got.

#47 [REQ-01] User registration and auth
  src/main/java/com/mercadolibre/dambetan01/config/WebSecurityConfig.java
  src/main/java/com/mercadolibre/dambetan01/controller/SessionController.java
  src/main/java/com/mercadolibre/dambetan01/dtos/AuthDTO.java
  src/main/java/com/mercadolibre/dambetan01/dtos/UserDTO.java
  src/main/java/com/mercadolibre/dambetan01/dtos/response/AccountResponseDTO.java
  src/main/java/com/mercadolibre/dambetan01/model/Account.java
  src/main/java/com/mercadolibre/dambetan01/model/User.java
  src/main/java/com/mercadolibre/dambetan01/model/enums/Profile.java
  src/main/java/com/mercadolibre/dambetan01/model/enums/Roles.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/UserService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/UserServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/SessionServiceImpl.java
  src/main/resources/db/migration/V20210702121249__Create_initial_structure.sql
  src/test/java/com/mercadolibre/dambetan01/unit/controller/SessionControllerTest.java
  src/test/java/com/mercadolibre/dambetan01/unit/service/SessionServiceImplTest.java
Labels: #REQ-01

#57 REQ-04 DTOS and deleting unused examples
  src/main/java/com/mercadolibre/dambetan01/beans/RandomSampleBean.java
  src/main/java/com/mercadolibre/dambetan01/controller/CountryHouseController.java
  src/main/java/com/mercadolibre/dambetan01/dtos/SampleDTO.java
  src/main/java/com/mercadolibre/dambetan01/dtos/WarehouseProductQuantityDTO.java
  src/main/java/com/mercadolibre/dambetan01/dtos/response/ProductsInWarehousesDTO.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/ICRUD.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/ICountryHouseService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/CountryHouseServiceImpl.java
  src/test/java/com/mercadolibre/dambetan01/unit/beans/RandomSampleBeanTest.java
Labels: #REQ-04, bug

#78 [REQ-02] resolving the bug of the price cart
  src/main/java/com/mercadolibre/dambetan01/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/dambetan01/dtos/response/PurchaseOrderResponseDTO.java
  src/main/java/com/mercadolibre/dambetan01/repository/PurchaseOrderRepository.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/PurchaseOrderContentService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/CartContentServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/PurchaseOrderContentServiceImpl.java
Labels: #REQ-02, Time: 2 Hours, feature

#79 Feature/cleaning code]
  dambetan01.iml
  src/main/java/com/mercadolibre/dambetan01/controller/ProductController.java
  src/main/java/com/mercadolibre/dambetan01/dtos/response/PurchaseOrderResponseDTO.java
  src/main/java/com/mercadolibre/dambetan01/model/PurchaseOrder.java
  src/main/java/com/mercadolibre/dambetan01/repository/OrderRepository.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/ProductService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/PurchaseService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/ProductServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/PurchaseServiceImpl.java
  src/test/java/com/mercadolibre/dambetan01/service/crud/impl/ProductServiceImplTest.java
  src/test/java/com/mercadolibre/dambetan01/service/crud/impl/PurchaseServiceImplTest.java
Labels: Time: 1 Hour, enhancement

#86 [REQ-02] Feature/req02 creating more validations
  src/main/java/com/mercadolibre/dambetan01/controller/CartController.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/CartContentService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/CartContentServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/PurchaseOrderContentServiceImpl.java
Labels: #REQ-02, Time: 3 Hours, feature
